#!/usr/bin/env bash

if [[ ! -f /var/mail/$USER ]]; then
    if [[ $OSTYPE = "darwin"* ]]; then
        sudo touch /var/mail/$USER
    else
        # Not sure if this will really work :)
        touch /var/mail/$USER
    fi
fi
