#!/bin/sh

# Run this script
set -eu

echo "xterm-256color|xterm with 256 colors and italic,
  sitm=\E[3m, ritm=\E[23m,
  use=xterm-256color," > xterm-256color.terminfo

tic -o ~/.terminfo xterm-256color.terminfo
rm xterm-256color.terminfo

# Run the following command to test italics:
# echo $(tput sitm)italics$(tput ritm)

# To see italics in vim, you'll need a newer version of vim than Apple provides
# - get it from MacPorts with: sudo port install vim
