#!/bin/bash
# This script symlinks the dotfiles defined in the 'dotfiles' variable to the
# home directory.

set -euo pipefail

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.

ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT

FILES_AND_DIRS_TO_SYMLINK=".vimrc .bash_profile .bash_aliases .mutt"
for f in $FILES_AND_DIRS_TO_SYMLINK; do
    ln -sf $ROOT/$f ~/$f
done
